DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${user}') THEN
      CREATE USER ${user} WITH password '${pwd}';
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS student;

GRANT USAGE ON SCHEMA student TO ${user};
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL tables IN SCHEMA student TO ${user};
ALTER DEFAULT PRIVILEGES IN SCHEMA student GRANT SELECT, INSERT, UPDATE, DELETE ON tables TO ${user};
ALTER DEFAULT PRIVILEGES IN SCHEMA student GRANT SELECT ON SEQUENCES TO ${user};
